[package]
name = "bgszc-events-server"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
fern = "0.7.1"
mysql = { version = "26.0.0", features = ["chrono"] }
rocket = "0.5.1"
serde = "1.0.218"
